/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as LayoutIndexRouteImport } from './routes/_layout/index'
import { Route as LayoutLoginRouteImport } from './routes/_layout/login'
import { Route as LayoutPageRouteImport } from './routes/_layout/_page'
import { Route as LayoutAuthenticatedRouteImport } from './routes/_layout/_authenticated'
import { Route as LayoutPageTermsOfServiceRouteImport } from './routes/_layout/_page/terms-of-service'
import { Route as LayoutPagePrivacyPolicyRouteImport } from './routes/_layout/_page/privacy-policy'
import { Route as LayoutAuthenticatedDashboardRouteImport } from './routes/_layout/_authenticated/dashboard'

const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutIndexRoute = LayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutLoginRoute = LayoutLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutPageRoute = LayoutPageRouteImport.update({
  id: '/_page',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAuthenticatedRoute = LayoutAuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutPageTermsOfServiceRoute =
  LayoutPageTermsOfServiceRouteImport.update({
    id: '/terms-of-service',
    path: '/terms-of-service',
    getParentRoute: () => LayoutPageRoute,
  } as any)
const LayoutPagePrivacyPolicyRoute = LayoutPagePrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => LayoutPageRoute,
} as any)
const LayoutAuthenticatedDashboardRoute =
  LayoutAuthenticatedDashboardRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => LayoutAuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/login': typeof LayoutLoginRoute
  '/': typeof LayoutIndexRoute
  '/dashboard': typeof LayoutAuthenticatedDashboardRoute
  '/privacy-policy': typeof LayoutPagePrivacyPolicyRoute
  '/terms-of-service': typeof LayoutPageTermsOfServiceRoute
}
export interface FileRoutesByTo {
  '/login': typeof LayoutLoginRoute
  '/': typeof LayoutIndexRoute
  '/dashboard': typeof LayoutAuthenticatedDashboardRoute
  '/privacy-policy': typeof LayoutPagePrivacyPolicyRoute
  '/terms-of-service': typeof LayoutPageTermsOfServiceRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_layout': typeof LayoutRouteWithChildren
  '/_layout/_authenticated': typeof LayoutAuthenticatedRouteWithChildren
  '/_layout/_page': typeof LayoutPageRouteWithChildren
  '/_layout/login': typeof LayoutLoginRoute
  '/_layout/': typeof LayoutIndexRoute
  '/_layout/_authenticated/dashboard': typeof LayoutAuthenticatedDashboardRoute
  '/_layout/_page/privacy-policy': typeof LayoutPagePrivacyPolicyRoute
  '/_layout/_page/terms-of-service': typeof LayoutPageTermsOfServiceRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/login'
    | '/'
    | '/dashboard'
    | '/privacy-policy'
    | '/terms-of-service'
  fileRoutesByTo: FileRoutesByTo
  to: '/login' | '/' | '/dashboard' | '/privacy-policy' | '/terms-of-service'
  id:
    | '__root__'
    | '/_layout'
    | '/_layout/_authenticated'
    | '/_layout/_page'
    | '/_layout/login'
    | '/_layout/'
    | '/_layout/_authenticated/dashboard'
    | '/_layout/_page/privacy-policy'
    | '/_layout/_page/terms-of-service'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LayoutRoute: typeof LayoutRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/login': {
      id: '/_layout/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LayoutLoginRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/_page': {
      id: '/_layout/_page'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof LayoutPageRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/_authenticated': {
      id: '/_layout/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof LayoutAuthenticatedRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/_page/terms-of-service': {
      id: '/_layout/_page/terms-of-service'
      path: '/terms-of-service'
      fullPath: '/terms-of-service'
      preLoaderRoute: typeof LayoutPageTermsOfServiceRouteImport
      parentRoute: typeof LayoutPageRoute
    }
    '/_layout/_page/privacy-policy': {
      id: '/_layout/_page/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof LayoutPagePrivacyPolicyRouteImport
      parentRoute: typeof LayoutPageRoute
    }
    '/_layout/_authenticated/dashboard': {
      id: '/_layout/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof LayoutAuthenticatedDashboardRouteImport
      parentRoute: typeof LayoutAuthenticatedRoute
    }
  }
}

interface LayoutAuthenticatedRouteChildren {
  LayoutAuthenticatedDashboardRoute: typeof LayoutAuthenticatedDashboardRoute
}

const LayoutAuthenticatedRouteChildren: LayoutAuthenticatedRouteChildren = {
  LayoutAuthenticatedDashboardRoute: LayoutAuthenticatedDashboardRoute,
}

const LayoutAuthenticatedRouteWithChildren =
  LayoutAuthenticatedRoute._addFileChildren(LayoutAuthenticatedRouteChildren)

interface LayoutPageRouteChildren {
  LayoutPagePrivacyPolicyRoute: typeof LayoutPagePrivacyPolicyRoute
  LayoutPageTermsOfServiceRoute: typeof LayoutPageTermsOfServiceRoute
}

const LayoutPageRouteChildren: LayoutPageRouteChildren = {
  LayoutPagePrivacyPolicyRoute: LayoutPagePrivacyPolicyRoute,
  LayoutPageTermsOfServiceRoute: LayoutPageTermsOfServiceRoute,
}

const LayoutPageRouteWithChildren = LayoutPageRoute._addFileChildren(
  LayoutPageRouteChildren,
)

interface LayoutRouteChildren {
  LayoutAuthenticatedRoute: typeof LayoutAuthenticatedRouteWithChildren
  LayoutPageRoute: typeof LayoutPageRouteWithChildren
  LayoutLoginRoute: typeof LayoutLoginRoute
  LayoutIndexRoute: typeof LayoutIndexRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutAuthenticatedRoute: LayoutAuthenticatedRouteWithChildren,
  LayoutPageRoute: LayoutPageRouteWithChildren,
  LayoutLoginRoute: LayoutLoginRoute,
  LayoutIndexRoute: LayoutIndexRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  LayoutRoute: LayoutRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
