/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as LayoutLoginRouteImport } from './routes/_layout/login'
import { Route as LayoutPageRouteImport } from './routes/_layout/_page'
import { Route as LayoutAuthenticatedRouteImport } from './routes/_layout/_authenticated'
import { Route as LayoutAuthenticatedIndexRouteImport } from './routes/_layout/_authenticated/index'
import { Route as LayoutPageTermsOfServiceRouteImport } from './routes/_layout/_page/terms-of-service'
import { Route as LayoutPagePrivacyPolicyRouteImport } from './routes/_layout/_page/privacy-policy'
import { Route as LayoutAuthenticatedAdminRouteImport } from './routes/_layout/_authenticated/_admin'
import { Route as LayoutAuthenticatedKeyRouteImport } from './routes/_layout/_authenticated/$key'
import { Route as LayoutAuthenticatedAdminDashboardRouteImport } from './routes/_layout/_authenticated/_admin/dashboard'

const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutLoginRoute = LayoutLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutPageRoute = LayoutPageRouteImport.update({
  id: '/_page',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAuthenticatedRoute = LayoutAuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAuthenticatedIndexRoute =
  LayoutAuthenticatedIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => LayoutAuthenticatedRoute,
  } as any)
const LayoutPageTermsOfServiceRoute =
  LayoutPageTermsOfServiceRouteImport.update({
    id: '/terms-of-service',
    path: '/terms-of-service',
    getParentRoute: () => LayoutPageRoute,
  } as any)
const LayoutPagePrivacyPolicyRoute = LayoutPagePrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => LayoutPageRoute,
} as any)
const LayoutAuthenticatedAdminRoute =
  LayoutAuthenticatedAdminRouteImport.update({
    id: '/_admin',
    getParentRoute: () => LayoutAuthenticatedRoute,
  } as any)
const LayoutAuthenticatedKeyRoute = LayoutAuthenticatedKeyRouteImport.update({
  id: '/$key',
  path: '/$key',
  getParentRoute: () => LayoutAuthenticatedRoute,
} as any)
const LayoutAuthenticatedAdminDashboardRoute =
  LayoutAuthenticatedAdminDashboardRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => LayoutAuthenticatedAdminRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/login': typeof LayoutLoginRoute
  '/$key': typeof LayoutAuthenticatedKeyRoute
  '/privacy-policy': typeof LayoutPagePrivacyPolicyRoute
  '/terms-of-service': typeof LayoutPageTermsOfServiceRoute
  '/': typeof LayoutAuthenticatedIndexRoute
  '/dashboard': typeof LayoutAuthenticatedAdminDashboardRoute
}
export interface FileRoutesByTo {
  '/login': typeof LayoutLoginRoute
  '/$key': typeof LayoutAuthenticatedKeyRoute
  '/privacy-policy': typeof LayoutPagePrivacyPolicyRoute
  '/terms-of-service': typeof LayoutPageTermsOfServiceRoute
  '/': typeof LayoutAuthenticatedIndexRoute
  '/dashboard': typeof LayoutAuthenticatedAdminDashboardRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_layout': typeof LayoutRouteWithChildren
  '/_layout/_authenticated': typeof LayoutAuthenticatedRouteWithChildren
  '/_layout/_page': typeof LayoutPageRouteWithChildren
  '/_layout/login': typeof LayoutLoginRoute
  '/_layout/_authenticated/$key': typeof LayoutAuthenticatedKeyRoute
  '/_layout/_authenticated/_admin': typeof LayoutAuthenticatedAdminRouteWithChildren
  '/_layout/_page/privacy-policy': typeof LayoutPagePrivacyPolicyRoute
  '/_layout/_page/terms-of-service': typeof LayoutPageTermsOfServiceRoute
  '/_layout/_authenticated/': typeof LayoutAuthenticatedIndexRoute
  '/_layout/_authenticated/_admin/dashboard': typeof LayoutAuthenticatedAdminDashboardRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/login'
    | '/$key'
    | '/privacy-policy'
    | '/terms-of-service'
    | '/'
    | '/dashboard'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/$key'
    | '/privacy-policy'
    | '/terms-of-service'
    | '/'
    | '/dashboard'
  id:
    | '__root__'
    | '/_layout'
    | '/_layout/_authenticated'
    | '/_layout/_page'
    | '/_layout/login'
    | '/_layout/_authenticated/$key'
    | '/_layout/_authenticated/_admin'
    | '/_layout/_page/privacy-policy'
    | '/_layout/_page/terms-of-service'
    | '/_layout/_authenticated/'
    | '/_layout/_authenticated/_admin/dashboard'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LayoutRoute: typeof LayoutRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/login': {
      id: '/_layout/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LayoutLoginRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/_page': {
      id: '/_layout/_page'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof LayoutPageRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/_authenticated': {
      id: '/_layout/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof LayoutAuthenticatedRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/_authenticated/': {
      id: '/_layout/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutAuthenticatedIndexRouteImport
      parentRoute: typeof LayoutAuthenticatedRoute
    }
    '/_layout/_page/terms-of-service': {
      id: '/_layout/_page/terms-of-service'
      path: '/terms-of-service'
      fullPath: '/terms-of-service'
      preLoaderRoute: typeof LayoutPageTermsOfServiceRouteImport
      parentRoute: typeof LayoutPageRoute
    }
    '/_layout/_page/privacy-policy': {
      id: '/_layout/_page/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof LayoutPagePrivacyPolicyRouteImport
      parentRoute: typeof LayoutPageRoute
    }
    '/_layout/_authenticated/_admin': {
      id: '/_layout/_authenticated/_admin'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof LayoutAuthenticatedAdminRouteImport
      parentRoute: typeof LayoutAuthenticatedRoute
    }
    '/_layout/_authenticated/$key': {
      id: '/_layout/_authenticated/$key'
      path: '/$key'
      fullPath: '/$key'
      preLoaderRoute: typeof LayoutAuthenticatedKeyRouteImport
      parentRoute: typeof LayoutAuthenticatedRoute
    }
    '/_layout/_authenticated/_admin/dashboard': {
      id: '/_layout/_authenticated/_admin/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof LayoutAuthenticatedAdminDashboardRouteImport
      parentRoute: typeof LayoutAuthenticatedAdminRoute
    }
  }
}

interface LayoutAuthenticatedAdminRouteChildren {
  LayoutAuthenticatedAdminDashboardRoute: typeof LayoutAuthenticatedAdminDashboardRoute
}

const LayoutAuthenticatedAdminRouteChildren: LayoutAuthenticatedAdminRouteChildren =
  {
    LayoutAuthenticatedAdminDashboardRoute:
      LayoutAuthenticatedAdminDashboardRoute,
  }

const LayoutAuthenticatedAdminRouteWithChildren =
  LayoutAuthenticatedAdminRoute._addFileChildren(
    LayoutAuthenticatedAdminRouteChildren,
  )

interface LayoutAuthenticatedRouteChildren {
  LayoutAuthenticatedKeyRoute: typeof LayoutAuthenticatedKeyRoute
  LayoutAuthenticatedAdminRoute: typeof LayoutAuthenticatedAdminRouteWithChildren
  LayoutAuthenticatedIndexRoute: typeof LayoutAuthenticatedIndexRoute
}

const LayoutAuthenticatedRouteChildren: LayoutAuthenticatedRouteChildren = {
  LayoutAuthenticatedKeyRoute: LayoutAuthenticatedKeyRoute,
  LayoutAuthenticatedAdminRoute: LayoutAuthenticatedAdminRouteWithChildren,
  LayoutAuthenticatedIndexRoute: LayoutAuthenticatedIndexRoute,
}

const LayoutAuthenticatedRouteWithChildren =
  LayoutAuthenticatedRoute._addFileChildren(LayoutAuthenticatedRouteChildren)

interface LayoutPageRouteChildren {
  LayoutPagePrivacyPolicyRoute: typeof LayoutPagePrivacyPolicyRoute
  LayoutPageTermsOfServiceRoute: typeof LayoutPageTermsOfServiceRoute
}

const LayoutPageRouteChildren: LayoutPageRouteChildren = {
  LayoutPagePrivacyPolicyRoute: LayoutPagePrivacyPolicyRoute,
  LayoutPageTermsOfServiceRoute: LayoutPageTermsOfServiceRoute,
}

const LayoutPageRouteWithChildren = LayoutPageRoute._addFileChildren(
  LayoutPageRouteChildren,
)

interface LayoutRouteChildren {
  LayoutAuthenticatedRoute: typeof LayoutAuthenticatedRouteWithChildren
  LayoutPageRoute: typeof LayoutPageRouteWithChildren
  LayoutLoginRoute: typeof LayoutLoginRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutAuthenticatedRoute: LayoutAuthenticatedRouteWithChildren,
  LayoutPageRoute: LayoutPageRouteWithChildren,
  LayoutLoginRoute: LayoutLoginRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  LayoutRoute: LayoutRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
